version: '3.5'

services:
    kotlin-restful-api-postgres:
      container_name: "kotlin-restful-api-postgres"
      image: postgres:12-alpine
      ports:
        - 5432:5432
      environment:
        POSTGRES_PASSWORD: peaceminusone
        POSTGRES_USER: peaceminusone
        POSTGRES_DB: peaceminusoneDB
